/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BranchingModelBranchTypes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class BranchingModelBranchTypes {
  /**
   * The kind of branch.
   */
  public enum KindEnum {
    FEATURE("feature"),
    BUGFIX("bugfix"),
    RELEASE("release"),
    HOTFIX("hotfix");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static KindEnum fromValue(String text) {
      for (KindEnum b : KindEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("kind")
  private KindEnum kind = null;

  @JsonProperty("prefix")
  private String prefix = null;

  public BranchingModelBranchTypes kind(KindEnum kind) {
    this.kind = kind;
    return this;
  }

   /**
   * The kind of branch.
   * @return kind
  **/
  @Schema(required = true, description = "The kind of branch.")
  public KindEnum getKind() {
    return kind;
  }

  public void setKind(KindEnum kind) {
    this.kind = kind;
  }

  public BranchingModelBranchTypes prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * The prefix for this branch type. A branch with this prefix will be classified as per &#x60;kind&#x60;. The prefix must be a valid prefix for a branch and must always exist. It cannot be blank, empty or &#x60;null&#x60;.
   * @return prefix
  **/
  @Schema(required = true, description = "The prefix for this branch type. A branch with this prefix will be classified as per `kind`. The prefix must be a valid prefix for a branch and must always exist. It cannot be blank, empty or `null`.")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchingModelBranchTypes branchingModelBranchTypes = (BranchingModelBranchTypes) o;
    return Objects.equals(this.kind, branchingModelBranchTypes.kind) &&
        Objects.equals(this.prefix, branchingModelBranchTypes.prefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, prefix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchingModelBranchTypes {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
