/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rappi.bitbucket.client.model.Commit;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * A file object, representing a file at a commit in a repository
 */
@Schema(description = "A file object, representing a file at a commit in a repository")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class CommitFile {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("commit")
  private Commit commit = null;

  /**
   * Gets or Sets attributes
   */
  public enum AttributesEnum {
    LINK("link"),
    EXECUTABLE("executable"),
    SUBREPOSITORY("subrepository"),
    BINARY("binary"),
    LFS("lfs");

    private String value;

    AttributesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AttributesEnum fromValue(String text) {
      for (AttributesEnum b : AttributesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("attributes")
  private AttributesEnum attributes = null;

  @JsonProperty("escaped_path")
  private String escapedPath = null;

  public CommitFile type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CommitFile path(String path) {
    this.path = path;
    return this;
  }

   /**
   * The path in the repository
   * @return path
  **/
  @Schema(description = "The path in the repository")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public CommitFile commit(Commit commit) {
    this.commit = commit;
    return this;
  }

   /**
   * Get commit
   * @return commit
  **/
  @Schema(description = "")
  public Commit getCommit() {
    return commit;
  }

  public void setCommit(Commit commit) {
    this.commit = commit;
  }

  public CommitFile attributes(AttributesEnum attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public AttributesEnum getAttributes() {
    return attributes;
  }

  public void setAttributes(AttributesEnum attributes) {
    this.attributes = attributes;
  }

  public CommitFile escapedPath(String escapedPath) {
    this.escapedPath = escapedPath;
    return this;
  }

   /**
   * The escaped version of the path as it appears in a diff. If the path does not require escaping this will be the same as path.
   * @return escapedPath
  **/
  @Schema(description = "The escaped version of the path as it appears in a diff. If the path does not require escaping this will be the same as path.")
  public String getEscapedPath() {
    return escapedPath;
  }

  public void setEscapedPath(String escapedPath) {
    this.escapedPath = escapedPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitFile commitFile = (CommitFile) o;
    return Objects.equals(this.type, commitFile.type) &&
        Objects.equals(this.path, commitFile.path) &&
        Objects.equals(this.commit, commitFile.commit) &&
        Objects.equals(this.attributes, commitFile.attributes) &&
        Objects.equals(this.escapedPath, commitFile.escapedPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, path, commit, attributes, escapedPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitFile {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    commit: ").append(toIndentedString(commit)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    escapedPath: ").append(toIndentedString(escapedPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
