/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rappi.bitbucket.client.model.DeploymentVariable;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * A paged list of deployment variables.
 */
@Schema(description = "A paged list of deployment variables.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class PaginatedDeploymentVariable {
  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("values")
  private List<DeploymentVariable> values = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("pagelen")
  private Integer pagelen = null;

  @JsonProperty("next")
  private String next = null;

  @JsonProperty("previous")
  private String previous = null;

  public PaginatedDeploymentVariable page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number of the current results. This is an optional element that is not provided in all responses.
   * @return page
  **/
  @Schema(description = "Page number of the current results. This is an optional element that is not provided in all responses.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public PaginatedDeploymentVariable values(List<DeploymentVariable> values) {
    this.values = values;
    return this;
  }

  public PaginatedDeploymentVariable addValuesItem(DeploymentVariable valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<DeploymentVariable>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The values of the current page.
   * @return values
  **/
  @Schema(description = "The values of the current page.")
  public List<DeploymentVariable> getValues() {
    return values;
  }

  public void setValues(List<DeploymentVariable> values) {
    this.values = values;
  }

  public PaginatedDeploymentVariable size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Total number of objects in the response. This is an optional element that is not provided in all responses, as it can be expensive to compute.
   * @return size
  **/
  @Schema(description = "Total number of objects in the response. This is an optional element that is not provided in all responses, as it can be expensive to compute.")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public PaginatedDeploymentVariable pagelen(Integer pagelen) {
    this.pagelen = pagelen;
    return this;
  }

   /**
   * Current number of objects on the existing page. The default value is 10 with 100 being the maximum allowed value. Individual APIs may enforce different values.
   * @return pagelen
  **/
  @Schema(description = "Current number of objects on the existing page. The default value is 10 with 100 being the maximum allowed value. Individual APIs may enforce different values.")
  public Integer getPagelen() {
    return pagelen;
  }

  public void setPagelen(Integer pagelen) {
    this.pagelen = pagelen;
  }

  public PaginatedDeploymentVariable next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Link to the next page if it exists. The last page of a collection does not have this value. Use this link to navigate the result set and refrain from constructing your own URLs.
   * @return next
  **/
  @Schema(description = "Link to the next page if it exists. The last page of a collection does not have this value. Use this link to navigate the result set and refrain from constructing your own URLs.")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public PaginatedDeploymentVariable previous(String previous) {
    this.previous = previous;
    return this;
  }

   /**
   * Link to previous page if it exists. A collections first page does not have this value. This is an optional element that is not provided in all responses. Some result sets strictly support forward navigation and never provide previous links. Clients must anticipate that backwards navigation is not always available. Use this link to navigate the result set and refrain from constructing your own URLs.
   * @return previous
  **/
  @Schema(description = "Link to previous page if it exists. A collections first page does not have this value. This is an optional element that is not provided in all responses. Some result sets strictly support forward navigation and never provide previous links. Clients must anticipate that backwards navigation is not always available. Use this link to navigate the result set and refrain from constructing your own URLs.")
  public String getPrevious() {
    return previous;
  }

  public void setPrevious(String previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginatedDeploymentVariable paginatedDeploymentVariable = (PaginatedDeploymentVariable) o;
    return Objects.equals(this.page, paginatedDeploymentVariable.page) &&
        Objects.equals(this.values, paginatedDeploymentVariable.values) &&
        Objects.equals(this.size, paginatedDeploymentVariable.size) &&
        Objects.equals(this.pagelen, paginatedDeploymentVariable.pagelen) &&
        Objects.equals(this.next, paginatedDeploymentVariable.next) &&
        Objects.equals(this.previous, paginatedDeploymentVariable.previous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, values, size, pagelen, next, previous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginatedDeploymentVariable {\n");
    
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    pagelen: ").append(toIndentedString(pagelen)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
