/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PipelineSelector
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class PipelineSelector extends Object {
  /**
   * The type of selector.
   */
  public enum TypeEnum {
    BRANCHES("branches"),
    TAGS("tags"),
    BOOKMARKS("bookmarks"),
    DEFAULT("default"),
    CUSTOM("custom");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("pattern")
  private String pattern = null;

  public PipelineSelector type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of selector.
   * @return type
  **/
  @Schema(description = "The type of selector.")
  public String getType() {
    return type.value;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public PipelineSelector pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * The name of the matching pipeline definition.
   * @return pattern
  **/
  @Schema(description = "The name of the matching pipeline definition.")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PipelineSelector pipelineSelector = (PipelineSelector) o;
    return Objects.equals(this.type, pipelineSelector.type) &&
        Objects.equals(this.pattern, pipelineSelector.pattern) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, pattern, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PipelineSelector {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
