/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rappi.bitbucket.client.model.IssueContent;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PullrequestRendered
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class PullrequestRendered {
  @JsonProperty("title")
  private IssueContent title = null;

  @JsonProperty("description")
  private IssueContent description = null;

  @JsonProperty("reason")
  private IssueContent reason = null;

  public PullrequestRendered title(IssueContent title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public IssueContent getTitle() {
    return title;
  }

  public void setTitle(IssueContent title) {
    this.title = title;
  }

  public PullrequestRendered description(IssueContent description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public IssueContent getDescription() {
    return description;
  }

  public void setDescription(IssueContent description) {
    this.description = description;
  }

  public PullrequestRendered reason(IssueContent reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @Schema(description = "")
  public IssueContent getReason() {
    return reason;
  }

  public void setReason(IssueContent reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullrequestRendered pullrequestRendered = (PullrequestRendered) o;
    return Objects.equals(this.title, pullrequestRendered.title) &&
        Objects.equals(this.description, pullrequestRendered.description) &&
        Objects.equals(this.reason, pullrequestRendered.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullrequestRendered {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
