/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.rappi.bitbucket.client.model.PullrequestEndpointBranch;
import com.rappi.bitbucket.client.model.PullrequestMergeCommit;
import com.rappi.bitbucket.client.model.Repository;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PullrequestEndpoint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class PullrequestEndpoint {
  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("branch")
  private PullrequestEndpointBranch branch = null;

  @JsonProperty("commit")
  private PullrequestMergeCommit commit = null;

  public PullrequestEndpoint repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  @Schema(description = "")
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public PullrequestEndpoint branch(PullrequestEndpointBranch branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @Schema(description = "")
  public PullrequestEndpointBranch getBranch() {
    return branch;
  }

  public void setBranch(PullrequestEndpointBranch branch) {
    this.branch = branch;
  }

  public PullrequestEndpoint commit(PullrequestMergeCommit commit) {
    this.commit = commit;
    return this;
  }

   /**
   * Get commit
   * @return commit
  **/
  @Schema(description = "")
  public PullrequestMergeCommit getCommit() {
    return commit;
  }

  public void setCommit(PullrequestMergeCommit commit) {
    this.commit = commit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullrequestEndpoint pullrequestEndpoint = (PullrequestEndpoint) o;
    return Objects.equals(this.repository, pullrequestEndpoint.repository) &&
        Objects.equals(this.branch, pullrequestEndpoint.branch) &&
        Objects.equals(this.commit, pullrequestEndpoint.commit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repository, branch, commit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullrequestEndpoint {\n");
    
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    commit: ").append(toIndentedString(commit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
