/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * WebhookSubscription
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-12T14:05:09.453-06:00[America/Mexico_City]")
public class WebhookSubscription extends Object {
  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("description")
  private String description = null;

  /**
   * The type of entity, which is &#x60;repository&#x60; in the case of webhook subscriptions on repositories.
   */
  public enum SubjectTypeEnum {
    WORKSPACE("workspace"),
    USER("user"),
    REPOSITORY("repository"),
    TEAM("team");

    private String value;

    SubjectTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SubjectTypeEnum fromValue(String text) {
      for (SubjectTypeEnum b : SubjectTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("subject_type")
  private SubjectTypeEnum subjectType = null;

  @JsonProperty("subject")
  private Object subject = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  /**
   * Gets or Sets events
   */
  public enum EventsEnum {
    PULLREQUEST_UNAPPROVED("pullrequest:unapproved"),
    ISSUE_COMMENT_CREATED("issue:comment_created"),
    PULLREQUEST_APPROVED("pullrequest:approved"),
    REPO_CREATED("repo:created"),
    REPO_DELETED("repo:deleted"),
    REPO_IMPORTED("repo:imported"),
    PULLREQUEST_COMMENT_UPDATED("pullrequest:comment_updated"),
    ISSUE_UPDATED("issue:updated"),
    PROJECT_UPDATED("project:updated"),
    PULLREQUEST_COMMENT_CREATED("pullrequest:comment_created"),
    REPO_COMMIT_STATUS_UPDATED("repo:commit_status_updated"),
    PULLREQUEST_UPDATED("pullrequest:updated"),
    ISSUE_CREATED("issue:created"),
    REPO_FORK("repo:fork"),
    PULLREQUEST_COMMENT_DELETED("pullrequest:comment_deleted"),
    REPO_COMMIT_STATUS_CREATED("repo:commit_status_created"),
    REPO_UPDATED("repo:updated"),
    PULLREQUEST_REJECTED("pullrequest:rejected"),
    PULLREQUEST_FULFILLED("pullrequest:fulfilled"),
    REPO_PUSH("repo:push"),
    PULLREQUEST_CREATED("pullrequest:created"),
    REPO_TRANSFER("repo:transfer"),
    REPO_COMMIT_COMMENT_CREATED("repo:commit_comment_created");

    private String value;

    EventsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EventsEnum fromValue(String text) {
      for (EventsEnum b : EventsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("events")
  private List<EventsEnum> events = null;

  public WebhookSubscription uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * The webhook&#x27;s id
   * @return uuid
  **/
  @Schema(description = "The webhook's id")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public WebhookSubscription url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL events get delivered to.
   * @return url
  **/
  @Schema(description = "The URL events get delivered to.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public WebhookSubscription description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A user-defined description of the webhook.
   * @return description
  **/
  @Schema(description = "A user-defined description of the webhook.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public WebhookSubscription subjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
    return this;
  }

   /**
   * The type of entity, which is &#x60;repository&#x60; in the case of webhook subscriptions on repositories.
   * @return subjectType
  **/
  @Schema(description = "The type of entity, which is `repository` in the case of webhook subscriptions on repositories.")
  public SubjectTypeEnum getSubjectType() {
    return subjectType;
  }

  public void setSubjectType(SubjectTypeEnum subjectType) {
    this.subjectType = subjectType;
  }

  public WebhookSubscription subject(Object subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @Schema(description = "")
  public Object getSubject() {
    return subject;
  }

  public void setSubject(Object subject) {
    this.subject = subject;
  }

  public WebhookSubscription active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public WebhookSubscription createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public WebhookSubscription events(List<EventsEnum> events) {
    this.events = events;
    return this;
  }

  public WebhookSubscription addEventsItem(EventsEnum eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<EventsEnum>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * The events this webhook is subscribed to.
   * @return events
  **/
  @Schema(description = "The events this webhook is subscribed to.")
  public List<EventsEnum> getEvents() {
    return events;
  }

  public void setEvents(List<EventsEnum> events) {
    this.events = events;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookSubscription webhookSubscription = (WebhookSubscription) o;
    return Objects.equals(this.uuid, webhookSubscription.uuid) &&
        Objects.equals(this.url, webhookSubscription.url) &&
        Objects.equals(this.description, webhookSubscription.description) &&
        Objects.equals(this.subjectType, webhookSubscription.subjectType) &&
        Objects.equals(this.subject, webhookSubscription.subject) &&
        Objects.equals(this.active, webhookSubscription.active) &&
        Objects.equals(this.createdAt, webhookSubscription.createdAt) &&
        Objects.equals(this.events, webhookSubscription.events) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, url, description, subjectType, subject, active, createdAt, events, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookSubscription {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
