/*
 * Bitbucket API
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@bitbucket.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.rappi.bitbucket.client.api;

import com.rappi.bitbucket.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SnippetApi
 */
@Ignore
public class SnippetApiTest {

    private final SnippetApi api = new SnippetApi();

    /**
     * 
     *
     * Convenience resource for getting to a snippet&#x27;s raw files without the need for first having to retrieve the snippet itself and having to pull out the versioned file links.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void snippetsWorkspaceEncodedIdFilesPathGetTest() {
        String encodedId = null;
        String path = null;
        String workspace = null;
        api.snippetsWorkspaceEncodedIdFilesPathGet(encodedId, path, workspace);

        // TODO: test validations
    }
}
